
import java.util.Timer;
import java.util.TimerTask;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Locke
 */


public class ClickerGame extends javax.swing.JFrame {

    int Debt = 1000000000;
    int PayableAmount = 1;
    int AutoPayableAmount = 1;
    int CountDown = 200;
    Timer timer = new Timer();
    Timer BarTimer = new Timer();
    
    TimerTask progressBarUpdate = new TimerTask() {
        @Override
        public void run() {
            barProgress.setValue(Debt);
        }
    };
    
    TimerTask AutoPayer = new TimerTask() {
        @Override
        public void run() {
            Debt -= AutoPayableAmount;
            if (Debt <= 0) {
                //you win and such
            } else {
                lblDebtAmount.setText(addCommas(Debt));
            }
        }
    };
    
    public void startBarUpdater() {
        BarTimer.scheduleAtFixedRate(progressBarUpdate,0,100);
    }

    
    /**
     * Creates new form ClickerGame
     */
    public ClickerGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        btnPayOffSomeDebt = new javax.swing.JButton();
        btnIncreasePayments = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblDebtAmount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barProgress = new javax.swing.JProgressBar();
        btnAutoPay = new javax.swing.JButton();
        lblAutoPayAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPayOffSomeDebt.setText("Pay off $1");
        btnPayOffSomeDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayOffSomeDebtActionPerformed(evt);
            }
        });

        btnIncreasePayments.setText("Increase Your Payments by $5");
        btnIncreasePayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreasePaymentsActionPerformed(evt);
            }
        });

        jButton3.setText("Reset all payments");

        lblDebtAmount.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblDebtAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDebtAmount.setText("1,000,000,000");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html> Resets all payments, but increases the amount of money you pay off the debt with </html>");

        barProgress.setMaximum(1000000000);
        barProgress.setValue(1000000000);

        btnAutoPay.setText("Buy an Auto Payer");
        btnAutoPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoPayActionPerformed(evt);
            }
        });

        lblAutoPayAmount.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDebtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPayOffSomeDebt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAutoPay)
                                .addGap(154, 154, 154))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncreasePayments)
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(barProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(lblAutoPayAmount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDebtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPayOffSomeDebt)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAutoPay)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnIncreasePayments))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAutoPayAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(barProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("Resets all payments, but increases the /n amount of money you pay off the debt with");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayOffSomeDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayOffSomeDebtActionPerformed
        
        Debt -= PayableAmount;
        if (Debt <= 0) {
            //you win and such
        } else {
            lblDebtAmount.setText(addCommas(Debt));
        }
        
    }//GEN-LAST:event_btnPayOffSomeDebtActionPerformed

    public static String addCommas(int x) {
        String firstThreeNumbers;
        String nextThreeNumbers;
        String nextNumbers;
        String s;
        
        s = String.valueOf(x);
        
        if (s.length() > 3 && s.length() < 7){
            
           firstThreeNumbers = s.substring(0,s.length() - 3);
           nextNumbers = s.substring(s.length() - 3,s.length());
           return firstThreeNumbers + "," + nextNumbers;
           
        } else if (s.length() > 6) {
            
            firstThreeNumbers = s.substring(0,s.length() - 6);
            nextThreeNumbers = s.substring(s.length() - 6, s.length() - 3);
            nextNumbers = s.substring(s.length() - 3);
            return firstThreeNumbers + "," + nextThreeNumbers + "," + nextNumbers;

        } else {
            return s;
            
        }
    }
    
    private void btnIncreasePaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreasePaymentsActionPerformed
        //if(Debt < 999)
        PayableAmount = PayableAmount + 50;
        AutoPayableAmount += 100;
        btnPayOffSomeDebt.setText("Pay off $" + PayableAmount);
        
    }//GEN-LAST:event_btnIncreasePaymentsActionPerformed

    private void btnAutoPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoPayActionPerformed
        
        //btnAutoPay.setVisible(false);
        int x = 1;
        
        timer.scheduleAtFixedRate(AutoPayer,CountDown,CountDown);
        
    }//GEN-LAST:event_btnAutoPayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //startBarUpdater();
        //LoanPayer Payer = new LoanPayer(1);
        //Debt MainDebt = new Debt(1000000000);
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClickerGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClickerGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClickerGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClickerGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClickerGame().setVisible(true);
            }
        });
    }
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barProgress;
    private javax.swing.JButton btnAutoPay;
    private javax.swing.JButton btnIncreasePayments;
    private javax.swing.JButton btnPayOffSomeDebt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblAutoPayAmount;
    private javax.swing.JLabel lblDebtAmount;
    // End of variables declaration//GEN-END:variables
}
